################ English language ##################
[en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1

# [pt]
# languageName = "Pt"
# languageCode = "pt-pt"
# contentDir = "content/portuguese"
# weight = 2
