on:
    push:
        branches:
        - main
name: Deploy website on push
jobs:
    web-deploy:
        name: Deploy
        runs-on: ubuntu-latest
        steps:
            - name: Get latest code
              uses: actions/checkout@v3

            - name: Push files
              uses: SamKirkland/FTP-Deploy-Action@v4.3.4
              with:
                server: myhosting.ua.pt
                username: ${{ secrets.ftp_user }}
                password: ${{ secrets.ftp_password }}
                protocol: ftps
                server-dir: /Hosting/ieee.web.ua.pt